# Generated by Django 4.0.6 on 2024-08-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(verbose_name='Data de Criação')),
                ('foto_perfil', models.ImageField(null=True, upload_to='profile', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('balancete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.balancete')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('foto_boleto', models.ImageField(upload_to='boletos')),
                ('balancete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.balancete')),
            ],
        ),
        migrations.AddField(
            model_name='balancete',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.useraccount'),
        ),
    ]
